### ISSUE TITLE
参数tk和cookie咋传？

### ISSUE THREAD

**Issue by qin1994** [xiangmingzhe0928/hpv4g#10]
直接跟在命令后面  如：python hpv4g ****（tk） ****(cookie)   ，还是怎样，我这样传参报错unrecognized arguments，希望大佬有时间回复一下  谢谢

**Comment by xiangmingzhe0928** [comment]
@qin1994 
通过`fiddler`抓包过后获取到`tk`和`cookie`

- 设抓包的`tk`为`12345`
- 设抓包的`cookie`为`abacdasf`
```
 执行 python hpv4g.py 12345 "abacdasf"
```

**Comment by qin1994** [comment]
好的&nbsp; 谢谢&nbsp; &nbsp;我抓到的cookie后面还有一部分内容和tk内容相同的，使用的是分号隔开，我把那部分内容删除，已经可以正常运行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiangmingzhe"<notifications@github.com&gt;; 
发送时间: 2021年1月6日(星期三) 上午9:54
收件人: "xiangmingzhe0928/hpv4g"<hpv4g@noreply.github.com&gt;; 
抄送: "四川"<535192465@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [xiangmingzhe0928/hpv4g] 参数tk和cookie咋传？ (#10)





 
@qin1994
 通过fiddler抓包过后获取到tk和cookie
  
设抓包的tk为12345
 
设抓包的cookie为abacdasf
   执行 python hpv4g.py 12345 "abacdasf"
