### ISSUE TITLE
关于ECC_HS的计算方式

### ISSUE THREAD

**Issue by pyk1998** [xiangmingzhe0928/hpv4g#11]
大佬脚本里的ECC_HS计算是采用了本地的时间戳计算的，但我通过反编译微信小程序，看到计算ECC_HS的时间戳是使用的查询库存时服务器返回的时间戳，不知道使用不同的时间戳会对程序逻辑有什么样的影响。

我有一个猜测是，小程序先调用库存查询接口，获得的时间戳，服务器也同步记录了，此后进入秒杀接口，服务器通过计算上一次用户的时间戳生成的ECC_HS，和此次提交的ECC_HS来验证用户的合法性。// 如果是这样逻辑就会很复杂

**Comment by xiangmingzhe0928** [comment]
@pyk1998 
是的 老哥 我当时也是反编译它的小程序看的~ 也纠结了很久😂 
但是并不真正知道它服务端 `ecc_hs`使用方式 而且在我看来他的盐是固定的 我觉得意义不大

最开始我也就是用的它的`checkstock`接口获取服务器的时间戳,  换本地时间后从秒杀响应结果看也是成功参与了秒杀的(但这里不知道它响应结果是不是笼统的) 
我觉得你猜想的方式可以试一试

**Comment by pyk1998** [comment]
@xiangmingzhe0928 
谢谢老哥回复
我先简单改了一个，下次成都放苗了测一下~

**Comment by pyk1998** [comment]
太难抢了233333333

**Comment by callmegaga** [comment]
> 大佬脚本里的ECC_HS计算是采用了本地的时间戳计算的，但我通过反编译微信小程序，看到计算ECC_HS的时间戳是使用的查询库存时服务器返回的时间戳，不知道使用不同的时间戳会对程序逻辑有什么样的影响。
> 
> 我有一个猜测是，小程序先调用库存查询接口，获得的时间戳，服务器也同步记录了，此后进入秒杀接口，服务器通过计算上一次用户的时间戳生成的ECC_HS，和此次提交的ECC_HS来验证用户的合法性。// 如果是这样逻辑就会很复杂

可以问一下，现在还能用的小程序反编译工具可以用哪个呢？
