### ISSUE TITLE
用不了了。老哥

### ISSUE THREAD

**Issue by Colin-Zhang** [xiangmingzhe0928/hpv4g#12]
ERROR:root:URL:https://miaomiao.scmttec.com/seckill/linkman/findByUserId.do ERROR:HTTPSConnectionPool(host='miaomiao.scmttec.com', port=443): Max retries exceeded with url: /seckill/linkman/findByUserId.do (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))

**Comment by pyk1998** [comment]
@Colin-Zhang 
把代理关掉试试？

**Comment by Colin-Zhang** [comment]
@pyk1998 可以了 之前是代理的问题，我把代理关掉发现还是运行有问题，要手动创建cache文件
