### ISSUE TITLE
秒杀前是这样的  请问是正常的吗？

### ISSUE THREAD

**Issue by yuzhongzhe001** [xiangmingzhe0928/hpv4g#13]
![image](https://user-images.githubusercontent.com/27844889/106992818-52736300-67b4-11eb-8bdb-531b4a00ed83.png)

**Comment by xiangmingzhe0928** [comment]
@yuzhongzhe001 
缓存文件夹找不到
可以在当前目录创建一个名叫`cache`的文件夹
后面有时间会改下这里
