### ISSUE TITLE
是知苗预约小程序还是约苗小程序，约苗好像只有公众号呢

### ISSUE THREAD

**Issue by hfw99** [xiangmingzhe0928/hpv4g#15]

**Comment by xiangmingzhe0928** [comment]
@hfw99 
官方把名字改了....
叫`秒苗`了
![image](https://user-images.githubusercontent.com/7719370/108490625-e594b880-72dd-11eb-93d2-2dbaf7f5865e.png)

---

但是你从`约苗`里面也能进到小程序
![image](https://user-images.githubusercontent.com/7719370/108491122-7a97b180-72de-11eb-979e-5de0db92e239.png)
