### ISSUE TITLE
想知道还能用么，token抓不到啊

### ISSUE THREAD

**Issue by qq4199** [xiangmingzhe0928/hpv4g#16]

**Comment by xiangmingzhe0928** [comment]
@qq4199 
试了下 还是可以抓包
<img width="566" alt="微信图片_20210303104824" src="https://user-images.githubusercontent.com/7719370/109744936-19d97480-7c0e-11eb-84fb-0faf2a374ede.png">

**Comment by hustStt** [comment]
> @qq4199
> 试了下 还是可以抓包
> <img alt="微信图片_20210303104824" width="566" src="https://user-images.githubusercontent.com/7719370/109744936-19d97480-7c0e-11eb-84fb-0faf2a374ede.png">

请问怎么抓包的，同局域网用pc抓手机的包吗？

**Comment by qq4199** [comment]
之前是抓错了，抓的另一个小程序的，现在这些抓是抓到了，但是现在是这样，群里能讨论吗
![image](https://user-images.githubusercontent.com/40818706/109757572-0685d380-7c25-11eb-9e6a-a55db02403c5.png)

**Comment by qq4199** [comment]
现在tk和cookie有了，但是请问要配置在哪些地方呢，是help后，还是直接改前面的。
![image](https://user-images.githubusercontent.com/40818706/109763783-8f087200-7c2d-11eb-92a5-0f5f8cdfb574.png)
下面这两个文件里的tk和cookie都要改么
![image](https://user-images.githubusercontent.com/40818706/109763976-e0186600-7c2d-11eb-9943-7cebbfb3b524.png)
@xiangmingzhe0928

**Comment by xiangmingzhe0928** [comment]
> > @qq4199
> > 试了下 还是可以抓包
> > <img alt="微信图片_20210303104824" width="566" src="https://user-images.githubusercontent.com/7719370/109744936-19d97480-7c0e-11eb-84fb-0faf2a374ede.png">
> 
> 请问怎么抓包的，同局域网用pc抓手机的包吗？

用PC登陆微信 电脑版上打开小程序 用`fiddler`抓

**Comment by qq4199** [comment]
是的，手机代理连接fiddler就可以了@hustStt

**Comment by xiangmingzhe0928** [comment]
> 现在tk和cookie有了，但是请问要配置在哪些地方呢，是help后，还是直接改前面的。
> ![image](https://user-images.githubusercontent.com/40818706/109763783-8f087200-7c2d-11eb-92a5-0f5f8cdfb574.png)
> 下面这两个文件里的tk和cookie都要改么
> ![image](https://user-images.githubusercontent.com/40818706/109763976-e0186600-7c2d-11eb-9943-7cebbfb3b524.png)
> @xiangmingzhe0928

老哥
不是去改代码里面 是在终端执行`python`文件的时候贴上去 
参考下`README`文档
