### ISSUE TITLE
cookie和token都及时抓包输进去了还是不对

### ISSUE THREAD

**Issue by qq4199** [xiangmingzhe0928/hpv4g#17]
![image](https://user-images.githubusercontent.com/40818706/110075978-adea3e00-7dbe-11eb-8708-b4411daa68a5.png)
终端命令是hpv4g.py tk "cookie"么

**Comment by xiangmingzhe0928** [comment]
@qq4199 
看截图 执行方式是对了的 
你抓包过后小程序不要退 退了会导致cookie失效
