### ISSUE TITLE
知苗预约上面能抢吗

### ISSUE THREAD

**Issue by hfw99** [xiangmingzhe0928/hpv4g#18]

**Comment by xiangmingzhe0928** [comment]
@hfw99 
Hi ! Sorry 没了解过`知苗`。
只能用在`约苗`上,, 不过原理都差不多, 有兴趣可以试试自己改

**Comment by hfw99** [comment]
好的，蟹蟹



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月29日(周一) 晚上6:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiangmingzhe0928/hpv4g] 知苗预约上面能抢吗 (#18)




 
@hfw99
 Hi ! Sorry 没了解过知苗。
 只能用在约苗上,, 不过原理都差不多, 有兴趣可以试试自己改
