### ISSUE TITLE
问下作者大哥，tk和cookie获取到了，在哪输入

### ISSUE THREAD

**Issue by spiderbin** [xiangmingzhe0928/hpv4g#19]

**Comment by xiangmingzhe0928** [comment]
@spiderbin 
直接贴到命令行作为参数运行 

---

通过`fiddler`抓包过后获取到`tk`和`cookie`

- 设抓包的`tk`为`12345`
- 设抓包的`cookie`为`abacdasf`
```
 执行 python hpv4g.py 12345 "abacdasf"
```
---
如果你用`fiddler`直接复制的`cookie`有可能带有空格 `python`会解析为2个不同的参数 所以建议直接用双引号包裹`cookie`
可以认真看下说明
