### ISSUE TITLE
非法请求,请登录授权后访问

### ISSUE THREAD

**Issue by jhhuang96** [xiangmingzhe0928/hpv4g#22]
![图片](https://user-images.githubusercontent.com/17799955/117525147-82204a00-aff3-11eb-9793-f3ae2e0eed83.png)
已经按要求输入tk 和 cookie，并且桌面版微信小程序保持打开状态

**Comment by xiangmingzhe0928** [comment]
@jhhuang96 
Hi~ 我这用`3201`正常的. 目测还是`tk/cookie`问题 
![image](https://user-images.githubusercontent.com/7719370/117527666-53f53700-b000-11eb-9b4d-fec87b94b17a.png)

**Comment by jhhuang96** [comment]
@xiangmingzhe0928 抓包入口搞错了，抓了预约的tk。
话说如果有苗预告时间，我需要提前多久打开脚本，等待预约呢？
