### ISSUE TITLE
那个自己的tk和cookie填在哪里啊。这个代码怎么改呢 

### ISSUE THREAD

**Issue by 850362564** [xiangmingzhe0928/hpv4g#24]
那个自己的tk和cookie填在哪里啊。这个代码怎么改呢 
![image](https://user-images.githubusercontent.com/74083293/137248360-3bcd4174-fd49-4756-9f98-fc894f15015b.png)

**Comment by xiangmingzhe0928** [comment]
老哥 不是修改代码 是终端运行的时候传入
可以参考下`README`文档
