### ISSUE TITLE
请问salt = ux$ad70*b 这个盐值是怎么知道的?

### ISSUE THREAD

**Issue by jiayaoO3O** [xiangmingzhe0928/hpv4g#25]
大佬我想请问一下, salt = ux$ad70*b这个盐值, 是通过小程序反编译知道写死在里面的吗?👨‍💻

**Comment by xiangmingzhe0928** [comment]
> 大佬我想请问一下, salt = ux$ad70*b这个盐值, 是通过小程序反编译知道写死在里面的吗?👨‍💻

@jiayaoO3O 


Hi 当时就是反编译它的小程序看的。当时的版本就是写死在小程序的。所以我觉得当时那个版本的`salt`有点鸡肋

---
这个已经很久没维护了 小程序应该都升级了

**Comment by jiayaoO3O** [comment]
是调用秒杀接口的时候要传这个ecc值吗? 我也准备开发新的秒杀脚本, 但是我没有见过调用秒杀接口的参数是什么样子的, 找不到哪个市现在可以秒杀的.

**Comment by xiangmingzhe0928** [comment]
@jiayaoO3O 
是在秒杀的接口里面传`ecc`的

---
可以考虑2种方案
-  抓包看你需要的接口
-  反编译直接看代码找api

---
>找不到哪个市现在可以秒杀的.

这个如果`約苗`小程序还能用的话 可以看下`scan_vaccine.py` 这个脚本是我当时随便写的一个用来扫描所有城市疫苗存货的脚本

**Comment by jiayaoO3O** [comment]
好的谢谢
