### ISSUE TITLE
点开文件就闪退

### ISSUE THREAD

**Issue by NAITUF** [xiangmingzhe0928/hpv4g#26]
我下载的是python 3.8，压缩包下载的文件，但点开hpv4g时就闪退，怎么回事？

**Comment by xiangmingzhe0928** [comment]
> 我下载的是python 3.8，压缩包下载的文件，但点开hpv4g时就闪退，怎么回事？

老哥 为什么要点开`hpv4g`?  
在控制台 `python`命令执行脚本啊。参考下`ReadMe`文档
