### ISSUE TITLE
fiddler现在怎么抓不到TK，需要用模拟器吗？

### ISSUE THREAD

**Issue by Gf1Hub** [xiangmingzhe0928/hpv4g#27]

**Comment by Gf1Hub** [comment]
求兄弟们指教指教

**Comment by lizhi-shenghuo** [comment]
要送饭吗

**Comment by xiangmingzhe0928** [comment]
> 求兄弟们指教指教

- 先确认下是否正确使用了`fiddler`，可以`google`一下使用方式
- 确认`fiddler`使用无误情况下 看看是不是`約苗`小程序更新了 （本仓库针对的当时的版本）

---

刚试了 现在还是可以抓到的`tk`的

**Comment by Gf1Hub** [comment]
谢谢，能抓到
