### ISSUE TITLE
为啥运行不起来，有交流群吗？

### ISSUE THREAD

**Issue by qq846511277** [xiangmingzhe0928/hpv4g#28]
为啥我放到pycharm里面运行不起来呀，有交流群吗？

**Comment by xiangmingzhe0928** [comment]
> 为啥我放到pycharm里面运行不起来呀，有交流群吗？

- 老铁 这就是个简单的脚本, 终端运行`hpv4g.py`即可,没必要在`pycharm`中运行。可以认真看下`README`

- 没有交流群，就是自己写来玩的小工具。小程序经常迭代更新也没准备长期维护。老哥确有需要可以看下`README`里面提到的其他几个`hpv`仓库

**Comment by qq846511277** [comment]
谢谢啦，第一次收到别人认真回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiangmingzhe0928/hpv4g"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 上午9:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiangmingzhe0928/hpv4g] 为啥运行不起来，有交流群吗？ (Issue #28)





  
为啥我放到pycharm里面运行不起来呀，有交流群吗？
   
 
老铁 这就是个简单的脚本, 终端运行hpv4g.py即可,没必要在pycharm中运行。可以认真看下README
 
 
 
没有交流群，就是自己写来玩的小工具。小程序经常迭代更新也没准备长期维护。老哥确有需要可以看下README里面提到的其他几个hpv仓库
 
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
