### ISSUE TITLE
研究了一天没啥进展，求助！

### ISSUE THREAD

**Issue by Cherishlifestyle** [xiangmingzhe0928/hpv4g#29]
您好，我将python hpv4g.py tk cookie 键入CMD （cd 路径），却总是错误（显示： No module named 'requests'）。我看您所展示的图片中，第一步是执行 hpv4g.py  ，第二步才是python hpv4g.py tk cookie ，这第一步我始终错误，也不知从何下手，希望能得到您解答。

**Comment by xiangmingzhe0928** [comment]
> 您好，我将python hpv4g.py tk cookie 键入CMD （cd 路径），却总是错误（显示： No module named 'requests'）。我看您所展示的图片中，第一步是执行 hpv4g.py ，第二步才是python hpv4g.py tk cookie ，这第一步我始终错误，也不知从何下手，希望能得到您解答。

Hi @Cherishlifestyle 
- `No module named 'requests'` 是因为脚本里面使用了第三方库`requests`。这个需要你检查一下本地是否安装了`request`，可以`pip install request`安装一下就可以了
- 执行脚本直接使用`python hpv4g.py tk cookie`

**Comment by Cherishlifestyle** [comment]
@xiangmingzhe0928  URL:https://miaomiao.scmttec.com/seckill/seckill/list.do ERROR:HTTPSConnectionPool(host='miaomiao.scmttec.com', port=443): Max retries exceeded with url: /seckill/seckill/list.do?offset=0&limit=10&regionCode=5101 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)')))

**Comment by xiangmingzhe0928** [comment]
> @xiangmingzhe0928 URL:https://miaomiao.scmttec.com/seckill/seckill/list.do ERROR:HTTPSConnectionPool(host='miaomiao.scmttec.com', port=443): Max retries exceeded with url: /seckill/seckill/list.do?offset=0&limit=10&regionCode=5101 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)')))

可以借鉴下这个issue:#4

**Comment by Cherishlifestyle** [comment]
> > @xiangmingzhe0928 URL:https://miaomiao.scmttec.com/seckill/seckill/list.do ERROR:HTTPSConnectionPool(host='miaomiao.scmttec.com', port=443): Max retries exceeded with url: /seckill/seckill/list.do?offset=0&limit=10&regionCode=5101 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)')))
> 
> 可以借鉴下这个issue:#4

已解决，谢谢
