### ISSUE TITLE
有兄弟成功抢到的吗？

### ISSUE THREAD

**Issue by azhuantou** [xiangmingzhe0928/hpv4g#30]
还是说这个代码已经失效了？我这一直跳出登陆超时
![image](https://user-images.githubusercontent.com/33474693/149891718-e69700c5-4dc3-4f89-b415-a3f178dc61ee.png)

**Comment by xiangmingzhe0928** [comment]
> 还是说这个代码已经失效了？我这一直跳出登陆超时 ![image](https://user-images.githubusercontent.com/33474693/149891718-e69700c5-4dc3-4f89-b415-a3f178dc61ee.png)

这是正常请求到服务了，错误信息是服务端返的。

**Comment by XiangMjjj** [comment]
同上，秒杀时提示用户登录超时，请重新登入，有哪些错误可能呢？

**Comment by jwli6** [comment]
cookie 总是变化，怎么解决啊？
